### ISSUE TITLE
Check before polyfilling

### ISSUE THREAD

**Issue by Fuzzyma** [rogodec/svg-innerhtml-polyfill#1]
This polyfill just overwrites whatever is there. It would be more sensible to check if innerHTML is available on the object before overwriting it

**Comment by djphan** [comment]
I recently had to use this polyfill for a quick IE11 solution, but if any person wants to implement a check a simple 

`if (!SVGElement.hasOwnProperty('innerHTML'))`

worked for me.

**Comment by rogodec** [comment]
fixed
